# Generated by Django 5.1.15 on 2026-09-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('published', 'Published'), ('healed', 'Healed and published'), ('blocked', 'Blocked -- failed closed'), ('error', 'Error')], default='running', max_length=12)),
                ('verdict', models.CharField(blank=True, max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_read', models.PositiveIntegerField(default=0)),
                ('records_published', models.PositiveIntegerField(default=0)),
                ('records_quarantined', models.PositiveIntegerField(default=0)),
                ('drift_detected', models.BooleanField(default=False)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='sources.mapping')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sources.source')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HealAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('promoted', 'Promoted'), ('rejected', 'Rejected by the proof gate'), ('failed', 'Healer could not produce a candidate')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('fixtures_total', models.PositiveIntegerField(default=0)),
                ('fixtures_passed', models.PositiveIntegerField(default=0)),
                ('fixture_results', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heals_to', to='sources.mapping')),
                ('from_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heals_from', to='sources.mapping')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heal_attempts', to='sources.source')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heal_attempts', to='pipeline.ingestionrun')),
            ],
            options={
                'ordering': ['attempt'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('published', 'Published'), ('quarantined', 'Quarantined'), ('withheld', 'Withheld -- batch failed closed')], max_length=12)),
                ('raw', models.JSONField(default=dict)),
                ('value', models.JSONField(default=dict)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pipeline.ingestionrun')),
            ],
            options={
                'ordering': ['index'],
                'indexes': [models.Index(fields=['run', 'status'], name='pipeline_ex_run_id_4efd5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warn', 'Warning'), ('block', 'Blocked'), ('ok', 'Success')], default='info', max_length=8)),
                ('code', models.SlugField(max_length=60)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pipeline.ingestionrun')),
            ],
            options={
                'ordering': ['seq'],
                'constraints': [models.UniqueConstraint(fields=('run', 'seq'), name='uniq_event_seq_per_run')],
            },
        ),
    ]
