# Generated by Django 5.1.15 on 2026-09-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('min_records', models.PositiveIntegerField(default=1)),
                ('unique_by', models.JSONField(blank=True, default=list)),
                ('continuity_threshold', models.FloatField(default=0.8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ContractField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80)),
                ('type', models.CharField(choices=[('string', 'string'), ('integer', 'integer'), ('number', 'number'), ('boolean', 'boolean'), ('date', 'date'), ('url', 'url'), ('email', 'email')], default='string', max_length=20)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('stable', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, max_length=200)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('min_fill_rate', models.FloatField(blank=True, null=True)),
                ('min_distinct_ratio', models.FloatField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='contracts.contract')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'name'), name='uniq_field_per_contract')],
            },
        ),
    ]
