"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-not-for-production")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'contracts',
    'demo',
    'sources',
    'pipeline',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Driftlock -------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True  # demo is public and read-only
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",") if o]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "frontend" / "dist"]
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_THROTTLE_RATES": {
        "run": os.environ.get("DRIFTLOCK_RUN_RATE", "15/hour"),
        "layout": os.environ.get("DRIFTLOCK_LAYOUT_RATE", "60/hour"),
    },
    # Render terminates TLS in front of the app, so the client address comes
    # from the forwarded header rather than the socket.
    "NUM_PROXIES": int(os.environ.get("DRIFTLOCK_NUM_PROXIES", "0")),
}

# The healer is the only component that spends money. Everything about it is
# bounded here so a runaway retry loop cannot quietly drain a budget.
DRIFTLOCK = {
    "ANTHROPIC_API_KEY": os.environ.get("ANTHROPIC_API_KEY", ""),
    "HEAL_MODEL": os.environ.get("DRIFTLOCK_HEAL_MODEL", "claude-opus-5"),
    "HEAL_MAX_ATTEMPTS": int(os.environ.get("DRIFTLOCK_HEAL_MAX_ATTEMPTS", "2")),
    "HEAL_MAX_USD_PER_RUN": float(os.environ.get("DRIFTLOCK_HEAL_MAX_USD_PER_RUN", "0.25")),
    # Ceiling on everything the public demo can spend in a rolling 24 hours.
    # Past it the pipeline keeps detecting drift and keeps failing closed;
    # it just stops paying for repairs.
    "PUBLIC_DAILY_USD_CAP": float(os.environ.get("DRIFTLOCK_PUBLIC_DAILY_USD_CAP", "1.00")),
    "HEAL_DOM_CHAR_BUDGET": int(os.environ.get("DRIFTLOCK_HEAL_DOM_CHARS", "40000")),
    # Where the demo storefront lives, so the pipeline reaches it over real HTTP
    # rather than through a shortcut the production path would not take.
    "DEMO_BASE_URL": os.environ.get("DRIFTLOCK_DEMO_BASE_URL", "http://127.0.0.1:8000"),
}

# DATABASE_ENGINE=sqlite wins over a DATABASE_URL still set on the host. The
# public demo runs on SQLite because Render deletes free Postgres databases
# after 30 days, and a dead URL would keep the app from booting.
if os.environ.get("DATABASE_URL") and os.environ.get("DATABASE_ENGINE", "").lower() != "sqlite":
    import dj_database_url
    DATABASES["default"] = dj_database_url.parse(
        os.environ["DATABASE_URL"], conn_max_age=600
    )

# --- production hardening --------------------------------------------------
# Only applied off DEBUG so local development stays plain HTTP.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
