# Generated by Django 5.1.15 on 2026-09-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.CharField(choices=[('v1', 'Original markup'), ('v2', 'Redesigned markup')], default='v1', max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
