# Generated by Django 5.1.15 on 2026-09-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demostate',
            name='layout',
            field=models.CharField(choices=[('v1', 'Original markup'), ('v2', 'Full redesign -- rows stop matching entirely'), ('v3', 'Silent break -- rows still match, two fields do not')], default='v1', max_length=4),
        ),
    ]
