# Generated by Django 5.1.15 on 2026-09-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('html', 'HTML page'), ('csv', 'CSV file')], max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='contracts.contract')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GoldenFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('records', models.JSONField(default=list)),
                ('raw', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='sources.source')),
            ],
            options={
                'ordering': ['-pinned', '-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('retired', 'Retired'), ('rejected', 'Rejected')], default='candidate', max_length=12)),
                ('origin', models.CharField(choices=[('human', 'Authored by a human'), ('heal', 'Proposed by the healer')], default='human', max_length=8)),
                ('rules', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sources.mapping')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='sources.source')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('source', 'version'), name='uniq_mapping_version')],
            },
        ),
    ]
